apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.5
    helm:
      releaseName: argocd # <<< important: adopt existing names
      valuesObject:
        server:
          service:
            type: ClusterIP
          ingress:
            enabled: false # Ingress is managed by your own YAML
          extraArgs:
            - --insecure
        configs:
          params:
            server.insecure: 'true'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
