apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '4.13.x'
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          replicaCount: 3
          nodeSelector:
            ingress-ready: "true"     # you already labeled the 3 workers
          service:
            type: LoadBalancer
            loadBalancerIP: 10.10.0.101
            externalTrafficPolicy: Local
          publishService:
            enabled: true
          admissionWebhooks:
            enabled: true
            patch:
              enabled: true
              image:
                registry: registry.k8s.io
                image: ingress-nginx/kube-webhook-certgen
                tag: v20240918
                pullPolicy: IfNotPresent
  ignoreDifferences:
    # ignore chart/patch-version label churn across ALL resources rendered by the chart
    - group: '*'
      kind: '*'
      jqPathExpressions:
        - .metadata.labels["helm.sh/chart"]
        - .metadata.labels["app.kubernetes.io/version"]
        - .metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
