apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          replicaCount: 3
          nodeSelector:
            ingress-ready: "true"
          publishService:
            enabled: true
          service:
            type: LoadBalancer
            loadBalancerIP: 10.10.0.101
            externalTrafficPolicy: Local
          # make CM render (non-empty config)
          config:
            use-forwarded-headers: "true"
          # TEMPORARY: disable hooks to unstick sync
          admissionWebhooks:
            enabled: false
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: ingress-nginx-controller
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - group: ""
      kind: Service
      name: ingress-nginx-controller
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - group: ""
      kind: Service
      name: ingress-nginx-controller-admission
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - group: ""
      kind: ServiceAccount
      name: ingress-nginx
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: ingress-nginx-admission
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
