apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: '*'
    helm:
      releaseName: gitea
      values: |
        # Force all Bitnami images to ghcr.io
        global:
          imageRegistry: ghcr.io

        ingress:
          enabled: false

        gitea:
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        # 🔽 Make Postgres pull from GHCR explicitly
        postgresql:
          enabled: true
          image:
            registry: ghcr.io
            repository: bitnami/postgresql
            tag: "16"
            pullPolicy: IfNotPresent
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
