apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.5 # pin the chart version you tested
    helm:
      # Use valuesObject to avoid quoting/escaping pitfalls
      valuesObject:
        server:
          enabled: true
          service:
            type: ClusterIP # no NodePort/LB; Ingress handles traffic
          ingress:
            enabled: false # Ingress is defined in your repo (argocd-ingress.yaml)
          extraArgs:
            - --insecure # Argo UI serves HTTP behind your edge TLS
        configs:
          params:
            server.insecure: 'true' # same as --insecure, via configmap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
