apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: '*' # or pin a version
    helm:
      releaseName: gitea
      values: |
        # Force all Bitnami subcharts to use GHCR instead of Docker Hub
        global:
          imageRegistry: ghcr.io

        ingress:
          enabled: false            # we keep our own Ingress manifest

        gitea:
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"      # TLS terminates on the Proxmox NGINX

        # (Optional) simplify by disabling Valkey while you bootstrap
        # valkey:
        #   enabled: false

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        postgresql:
          enabled: true
          image:
            repository: bitnami/postgresql
            tag: "16"
            pullPolicy: IfNotPresent
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
