apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    helm:
      dependencyUpdate: true
      values: |
        ingress:
          enabled: false

        gitea:
          cache:
            enabled: false
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        # allow chart to accept non-original registry (GHCR)
        global:
          security:
            allowInsecureImages: true

        postgresql:
          enabled: true
          fullnameOverride: gitea-postgresql
          image:
            registry: ghcr.io
            repository: bitnami/postgresql
            tag: "16"            # if this still fails, see note below
            pullPolicy: IfNotPresent
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
