apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: '*' # or pin a version you prefer
    helm:
      releaseName: gitea
      values: |
        ingress:
          enabled: false              # we bring our own Ingress below

        gitea:
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"        # TLS is terminated on the Proxmox NGINX

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        postgresql:
          enabled: true
          image:
            registry: docker.io         # or try ghcr.io if Docker Hub is blocked/rate-limited
            repository: bitnami/postgresql
            tag: "16.4.0"
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false              # <- IMPORTANT

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
