apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.5 # pin a version you’re happy with
    helm:
      parameters:
        # IMPORTANT: let your standalone YAML own the Ingress
        - name: server.ingress.enabled
          value: 'false'

        # TLS is terminated on the Proxmox NGINX reverse-proxy
        - name: configs.params.server\.insecure
          value: 'true'
        # (optional) also pass the flag via extraArgs
        - name: server.extraArgs[0]
          value: --insecure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
