apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  source:
    helm:
      dependencyUpdate: true
      values: |
        ingress:
          enabled: false

        gitea:
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        # apply to subcharts too
        global:
          imageRegistry: ghcr.io
          security:
            allowInsecureImages: true

        postgresql:
          enabled: true
          # *** change this to force a new object name ***
          fullnameOverride: gitea-pg-3
          image:
            registry: ghcr.io
            repository: bitnami/postgresql
            tag: "17"                  # pick a real GHCR tag; "17" is widely available
            pullPolicy: IfNotPresent
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
