apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '*'
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          replicaCount: 3
          nodeSelector:
            ingress-ready: "true"     # you already labeled the 3 workers
          service:
            type: LoadBalancer
            loadBalancerIP: 10.10.0.101
            externalTrafficPolicy: Local
          publishService:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
