apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-helm
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: '*' # keep or pin
    helm:
      releaseName: gitea
      values: |
        ingress:
          enabled: false          # we keep our own Ingress manifest

        gitea:
          config:
            server:
              ROOT_URL: "https://gitea-labnum.aphp.fr/"
              DOMAIN: "gitea-labnum.aphp.fr"
              PROTOCOL: "http"    # TLS ends on Proxmox NGINX

        # OPTIONAL: you can disable valkey to simplify
        # valkey:
        #   enabled: false

        persistence:
          enabled: true
          size: 10Gi
          accessModes: ["ReadWriteOnce"]
          storageClass: longhorn

        postgresql:
          enabled: true
          image:
            registry: ghcr.io
            repository: bitnami/postgresql
            tag: "16"            # stable, widely available
            pullPolicy: IfNotPresent
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: longhorn

        postgresql-ha:
          enabled: false
