apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: REPO_URL   # ⬅️ Remplacer par l'URL Git de ce dépôt
    targetRevision: HEAD
    path: ressources/platform/apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
